
version: '3.3'

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=operator
      - POSTGRES_PASSWORD=CastAIP
    ports:
      - 2282:5432
    networks:
      - castaip
    volumes:
      - ./postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./data:/var/lib/postgresql/data
      - ./logs:/logs
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - castaip

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=pgAdminPwd
      - PGADMIN_DEFAULT_EMAIL=fx.albouy@castsoftware.com
      - PGADMIN_LISTEN_PORT=80
    networks:
      - castaip

networks:
  castaip:
    driver: bridge

volumes:
  postgresql:
  data:
  logs:
    
