
version: '3.3'

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=operator
      - POSTGRES_PASSWORD=CastAIP
    ports:
      - 2282:5432
    networks:
      - castaip
    command: postgres -c listen_addresses='*' -c Port=5432 -c max_connections=300 -c temp_buffers=32MB -c work_mem=64MB -c maintenance_work_mem=1024MB -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c commit_delay=10 -c checkpoint_completion_target=0.9 -c cursor_tuple_fraction=1  -c log_checkpoints=on  -c log_destination='stderr'  -c logging_collector=on  -c log_temp_files=1024kB -c log_autovacuum_min_duration=1000ms -c autovacuum_vacuum_cost_limit=200 -c bytea_output='escape' -c lc_messages='C' -c lc_monetary='C' -c lc_numeric='C' -c lc_time='C' -c max_locks_per_transaction=4096 -c standard_conforming_strings=on
    volumes:
      - ./data/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - data_postgres:/var/lib/postgresql/data
      - ./logs:/logs
      

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=pgAdminPwd
      - PGADMIN_DEFAULT_EMAIL=fx.albouy@castsoftware.com
      - PGADMIN_LISTEN_PORT=80
    networks:
      - castaip

networks:
  castaip:
    driver: bridge

volumes:
  postgresql:
  data_postgres:
    external: true
  logs:
